name: event messages
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            📥 **NUOVO AGGIORNAMENTO**
            *Progetto: ${{ EVENT_PAYLOAD.repository.full_name }}*
            `Autore: ${{ github.actor }}`
            
            ${{ github.event.commits[0].message }}
